//
//  HomeScreenSceneInteractor.swift
//  WeatherApp
//
//  Created by FARIT GATIATULLIN on 09.06.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol HomeScreenSceneBusinessLogic
{
  func doSomething(request: HomeScreenScene.Something.Request)
}

protocol HomeScreenSceneDataStore
{
  //var name: String { get set }
}

class HomeScreenSceneInteractor: HomeScreenSceneBusinessLogic, HomeScreenSceneDataStore
{
  var presenter: HomeScreenScenePresentationLogic?
  var worker: HomeScreenSceneWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: HomeScreenScene.Something.Request)
  {
    worker = HomeScreenSceneWorker()
    worker?.doSomeWork()
    
    let response = HomeScreenScene.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
